# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from sqala_python_sdk import Sqala

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        sqala = Sqala(
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD'
        )
        self.assertIsNotNone(sqala)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
