# coding: utf-8

# flake8: noqa

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0"

# import ApiClient
from sqala_python_sdk.api_client import ApiClient

# import Configuration
from sqala_python_sdk.configuration import Configuration

# import exceptions
from sqala_python_sdk.exceptions import OpenApiException
from sqala_python_sdk.exceptions import ApiAttributeError
from sqala_python_sdk.exceptions import ApiTypeError
from sqala_python_sdk.exceptions import ApiValueError
from sqala_python_sdk.exceptions import ApiKeyError
from sqala_python_sdk.exceptions import ApiException

from sqala_python_sdk.client import Sqala
