# coding: utf-8
"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from sqala_python_sdk.client_custom import ClientCustom
from sqala_python_sdk.configuration import Configuration
from sqala_python_sdk.api_client import ApiClient
from sqala_python_sdk.type_util import copy_signature
from sqala_python_sdk.apis.tags.bank_transfer_api import BankTransferApi
from sqala_python_sdk.apis.tags.itp_api import ITPApi
from sqala_python_sdk.apis.tags.qr_code_api import QRCodeApi
from sqala_python_sdk.apis.tags.recipient_api import RecipientApi
from sqala_python_sdk.apis.tags.token_api import TokenApi
from sqala_python_sdk.apis.tags.webhook_api import WebhookApi



class Sqala(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.bank_transfer: BankTransferApi = BankTransferApi(api_client)
        self.itp: ITPApi = ITPApi(api_client)
        self.qr_code: QRCodeApi = QRCodeApi(api_client)
        self.recipient: RecipientApi = RecipientApi(api_client)
        self.token: TokenApi = TokenApi(api_client)
        self.webhook: WebhookApi = WebhookApi(api_client)
