# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import sqala_python_sdk
from sqala_python_sdk.model.token_generate_access_token_response import TokenGenerateAccessTokenResponse
from sqala_python_sdk import configuration


class TestTokenGenerateAccessTokenResponse(unittest.TestCase):
    """TokenGenerateAccessTokenResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
