# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sqala_python_sdk import schemas  # noqa: F401


class QrCodeGenerateQrCodeRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "amount",
        }
        
        class properties:
            amount = schemas.Int32Schema
            code = schemas.StrSchema
        
            @staticmethod
            def payer() -> typing.Type['QrCodeGenerateQrCodeRequestPayer']:
                return QrCodeGenerateQrCodeRequestPayer
        
            @staticmethod
            def split() -> typing.Type['QrCodeGenerateQrCodeRequestSplit']:
                return QrCodeGenerateQrCodeRequestSplit
        
            @staticmethod
            def metadata() -> typing.Type['QrCodeGenerateQrCodeRequestMetadata']:
                return QrCodeGenerateQrCodeRequestMetadata
            __annotations__ = {
                "amount": amount,
                "code": code,
                "payer": payer,
                "split": split,
                "metadata": metadata,
            }
    
    amount: MetaOapg.properties.amount
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payer"]) -> 'QrCodeGenerateQrCodeRequestPayer': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["split"]) -> 'QrCodeGenerateQrCodeRequestSplit': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> 'QrCodeGenerateQrCodeRequestMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["amount", "code", "payer", "split", "metadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payer"]) -> typing.Union['QrCodeGenerateQrCodeRequestPayer', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["split"]) -> typing.Union['QrCodeGenerateQrCodeRequestSplit', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union['QrCodeGenerateQrCodeRequestMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["amount", "code", "payer", "split", "metadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, ],
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        payer: typing.Union['QrCodeGenerateQrCodeRequestPayer', schemas.Unset] = schemas.unset,
        split: typing.Union['QrCodeGenerateQrCodeRequestSplit', schemas.Unset] = schemas.unset,
        metadata: typing.Union['QrCodeGenerateQrCodeRequestMetadata', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'QrCodeGenerateQrCodeRequest':
        return super().__new__(
            cls,
            *args,
            amount=amount,
            code=code,
            payer=payer,
            split=split,
            metadata=metadata,
            _configuration=_configuration,
            **kwargs,
        )

from sqala_python_sdk.model.qr_code_generate_qr_code_request_metadata import QrCodeGenerateQrCodeRequestMetadata
from sqala_python_sdk.model.qr_code_generate_qr_code_request_payer import QrCodeGenerateQrCodeRequestPayer
from sqala_python_sdk.model.qr_code_generate_qr_code_request_split import QrCodeGenerateQrCodeRequestSplit
