# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sqala_python_sdk import schemas  # noqa: F401


class RecipientCreateWithdrawalRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "amount",
            "method",
        }
        
        class properties:
            amount = schemas.Int32Schema
            
            
            class method(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def STANDARD(cls):
                    return cls("STANDARD")
                
                @schemas.classproperty
                def PIX(cls):
                    return cls("PIX")
            code = schemas.StrSchema
            pixKey = schemas.StrSchema
        
            @staticmethod
            def bankAccount() -> typing.Type['RecipientCreateWithdrawalRequestBankAccount']:
                return RecipientCreateWithdrawalRequestBankAccount
            bankAccountId = schemas.StrSchema
        
            @staticmethod
            def metadata() -> typing.Type['RecipientCreateWithdrawalRequestMetadata']:
                return RecipientCreateWithdrawalRequestMetadata
            __annotations__ = {
                "amount": amount,
                "method": method,
                "code": code,
                "pixKey": pixKey,
                "bankAccount": bankAccount,
                "bankAccountId": bankAccountId,
                "metadata": metadata,
            }
    
    amount: MetaOapg.properties.amount
    method: MetaOapg.properties.method
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method"]) -> MetaOapg.properties.method: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pixKey"]) -> MetaOapg.properties.pixKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bankAccount"]) -> 'RecipientCreateWithdrawalRequestBankAccount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bankAccountId"]) -> MetaOapg.properties.bankAccountId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> 'RecipientCreateWithdrawalRequestMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["amount", "method", "code", "pixKey", "bankAccount", "bankAccountId", "metadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method"]) -> MetaOapg.properties.method: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pixKey"]) -> typing.Union[MetaOapg.properties.pixKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bankAccount"]) -> typing.Union['RecipientCreateWithdrawalRequestBankAccount', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bankAccountId"]) -> typing.Union[MetaOapg.properties.bankAccountId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union['RecipientCreateWithdrawalRequestMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["amount", "method", "code", "pixKey", "bankAccount", "bankAccountId", "metadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, ],
        method: typing.Union[MetaOapg.properties.method, str, ],
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        pixKey: typing.Union[MetaOapg.properties.pixKey, str, schemas.Unset] = schemas.unset,
        bankAccount: typing.Union['RecipientCreateWithdrawalRequestBankAccount', schemas.Unset] = schemas.unset,
        bankAccountId: typing.Union[MetaOapg.properties.bankAccountId, str, schemas.Unset] = schemas.unset,
        metadata: typing.Union['RecipientCreateWithdrawalRequestMetadata', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RecipientCreateWithdrawalRequest':
        return super().__new__(
            cls,
            *args,
            amount=amount,
            method=method,
            code=code,
            pixKey=pixKey,
            bankAccount=bankAccount,
            bankAccountId=bankAccountId,
            metadata=metadata,
            _configuration=_configuration,
            **kwargs,
        )

from sqala_python_sdk.model.recipient_create_withdrawal_request_bank_account import RecipientCreateWithdrawalRequestBankAccount
from sqala_python_sdk.model.recipient_create_withdrawal_request_metadata import RecipientCreateWithdrawalRequestMetadata
