# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sqala_python_sdk import schemas  # noqa: F401


class RecipientCreateWithdrawalRequestBankAccount(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The destination bank account. Required if method is STANDARD.
    """


    class MetaOapg:
        required = {
            "bankId",
            "holderName",
            "branchNumber",
            "holderTaxId",
            "accountNumber",
            "holderType",
        }
        
        class properties:
            holderName = schemas.StrSchema
            holderTaxId = schemas.StrSchema
            
            
            class holderType(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def INDIVIDUAL(cls):
                    return cls("INDIVIDUAL")
                
                @schemas.classproperty
                def COMPANY(cls):
                    return cls("COMPANY")
            branchNumber = schemas.StrSchema
            accountNumber = schemas.StrSchema
            bankId = schemas.StrSchema
            
            
            class type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def CHECKING(cls):
                    return cls("CHECKING")
                
                @schemas.classproperty
                def SAVINGS(cls):
                    return cls("SAVINGS")
            __annotations__ = {
                "holderName": holderName,
                "holderTaxId": holderTaxId,
                "holderType": holderType,
                "branchNumber": branchNumber,
                "accountNumber": accountNumber,
                "bankId": bankId,
                "type": type,
            }
    
    bankId: MetaOapg.properties.bankId
    holderName: MetaOapg.properties.holderName
    branchNumber: MetaOapg.properties.branchNumber
    holderTaxId: MetaOapg.properties.holderTaxId
    accountNumber: MetaOapg.properties.accountNumber
    holderType: MetaOapg.properties.holderType
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["holderName"]) -> MetaOapg.properties.holderName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["holderTaxId"]) -> MetaOapg.properties.holderTaxId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["holderType"]) -> MetaOapg.properties.holderType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["branchNumber"]) -> MetaOapg.properties.branchNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accountNumber"]) -> MetaOapg.properties.accountNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bankId"]) -> MetaOapg.properties.bankId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["holderName", "holderTaxId", "holderType", "branchNumber", "accountNumber", "bankId", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["holderName"]) -> MetaOapg.properties.holderName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["holderTaxId"]) -> MetaOapg.properties.holderTaxId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["holderType"]) -> MetaOapg.properties.holderType: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["branchNumber"]) -> MetaOapg.properties.branchNumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accountNumber"]) -> MetaOapg.properties.accountNumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bankId"]) -> MetaOapg.properties.bankId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["holderName", "holderTaxId", "holderType", "branchNumber", "accountNumber", "bankId", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        bankId: typing.Union[MetaOapg.properties.bankId, str, ],
        holderName: typing.Union[MetaOapg.properties.holderName, str, ],
        branchNumber: typing.Union[MetaOapg.properties.branchNumber, str, ],
        holderTaxId: typing.Union[MetaOapg.properties.holderTaxId, str, ],
        accountNumber: typing.Union[MetaOapg.properties.accountNumber, str, ],
        holderType: typing.Union[MetaOapg.properties.holderType, str, ],
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RecipientCreateWithdrawalRequestBankAccount':
        return super().__new__(
            cls,
            *args,
            bankId=bankId,
            holderName=holderName,
            branchNumber=branchNumber,
            holderTaxId=holderTaxId,
            accountNumber=accountNumber,
            holderType=holderType,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )
