# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sqala_python_sdk import schemas  # noqa: F401


class RecipientCreateWithdrawalResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            id = schemas.StrSchema
            code = schemas.StrSchema
            amount = schemas.IntSchema
            method = schemas.StrSchema
            status = schemas.StrSchema
            createdAt = schemas.StrSchema
            approvedAt = schemas.StrSchema
            rejectedAt = schemas.AnyTypeSchema
            processedAt = schemas.StrSchema
            paidAt = schemas.AnyTypeSchema
            failedAt = schemas.AnyTypeSchema
            pixKey = schemas.AnyTypeSchema
        
            @staticmethod
            def bankAccount() -> typing.Type['RecipientCreateWithdrawalResponseBankAccount']:
                return RecipientCreateWithdrawalResponseBankAccount
        
            @staticmethod
            def recipient() -> typing.Type['RecipientCreateWithdrawalResponseRecipient']:
                return RecipientCreateWithdrawalResponseRecipient
        
            @staticmethod
            def metadata() -> typing.Type['RecipientCreateWithdrawalResponseMetadata']:
                return RecipientCreateWithdrawalResponseMetadata
            __annotations__ = {
                "id": id,
                "code": code,
                "amount": amount,
                "method": method,
                "status": status,
                "createdAt": createdAt,
                "approvedAt": approvedAt,
                "rejectedAt": rejectedAt,
                "processedAt": processedAt,
                "paidAt": paidAt,
                "failedAt": failedAt,
                "pixKey": pixKey,
                "bankAccount": bankAccount,
                "recipient": recipient,
                "metadata": metadata,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method"]) -> MetaOapg.properties.method: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["approvedAt"]) -> MetaOapg.properties.approvedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rejectedAt"]) -> MetaOapg.properties.rejectedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["processedAt"]) -> MetaOapg.properties.processedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paidAt"]) -> MetaOapg.properties.paidAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failedAt"]) -> MetaOapg.properties.failedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pixKey"]) -> MetaOapg.properties.pixKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bankAccount"]) -> 'RecipientCreateWithdrawalResponseBankAccount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recipient"]) -> 'RecipientCreateWithdrawalResponseRecipient': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> 'RecipientCreateWithdrawalResponseMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "code", "amount", "method", "status", "createdAt", "approvedAt", "rejectedAt", "processedAt", "paidAt", "failedAt", "pixKey", "bankAccount", "recipient", "metadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union[MetaOapg.properties.amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method"]) -> typing.Union[MetaOapg.properties.method, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> typing.Union[MetaOapg.properties.createdAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["approvedAt"]) -> typing.Union[MetaOapg.properties.approvedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rejectedAt"]) -> typing.Union[MetaOapg.properties.rejectedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["processedAt"]) -> typing.Union[MetaOapg.properties.processedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paidAt"]) -> typing.Union[MetaOapg.properties.paidAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failedAt"]) -> typing.Union[MetaOapg.properties.failedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pixKey"]) -> typing.Union[MetaOapg.properties.pixKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bankAccount"]) -> typing.Union['RecipientCreateWithdrawalResponseBankAccount', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recipient"]) -> typing.Union['RecipientCreateWithdrawalResponseRecipient', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union['RecipientCreateWithdrawalResponseMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "code", "amount", "method", "status", "createdAt", "approvedAt", "rejectedAt", "processedAt", "paidAt", "failedAt", "pixKey", "bankAccount", "recipient", "metadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        method: typing.Union[MetaOapg.properties.method, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, schemas.Unset] = schemas.unset,
        approvedAt: typing.Union[MetaOapg.properties.approvedAt, str, schemas.Unset] = schemas.unset,
        rejectedAt: typing.Union[MetaOapg.properties.rejectedAt, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        processedAt: typing.Union[MetaOapg.properties.processedAt, str, schemas.Unset] = schemas.unset,
        paidAt: typing.Union[MetaOapg.properties.paidAt, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        failedAt: typing.Union[MetaOapg.properties.failedAt, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        pixKey: typing.Union[MetaOapg.properties.pixKey, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        bankAccount: typing.Union['RecipientCreateWithdrawalResponseBankAccount', schemas.Unset] = schemas.unset,
        recipient: typing.Union['RecipientCreateWithdrawalResponseRecipient', schemas.Unset] = schemas.unset,
        metadata: typing.Union['RecipientCreateWithdrawalResponseMetadata', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RecipientCreateWithdrawalResponse':
        return super().__new__(
            cls,
            *args,
            id=id,
            code=code,
            amount=amount,
            method=method,
            status=status,
            createdAt=createdAt,
            approvedAt=approvedAt,
            rejectedAt=rejectedAt,
            processedAt=processedAt,
            paidAt=paidAt,
            failedAt=failedAt,
            pixKey=pixKey,
            bankAccount=bankAccount,
            recipient=recipient,
            metadata=metadata,
            _configuration=_configuration,
            **kwargs,
        )

from sqala_python_sdk.model.recipient_create_withdrawal_response_bank_account import RecipientCreateWithdrawalResponseBankAccount
from sqala_python_sdk.model.recipient_create_withdrawal_response_metadata import RecipientCreateWithdrawalResponseMetadata
from sqala_python_sdk.model.recipient_create_withdrawal_response_recipient import RecipientCreateWithdrawalResponseRecipient
