# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sqala_python_sdk import schemas  # noqa: F401


class RecipientListWithdrawalsResponseDataItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            id = schemas.StrSchema
            code = schemas.StrSchema
            amount = schemas.IntSchema
            method = schemas.StrSchema
            status = schemas.StrSchema
            createdAt = schemas.StrSchema
            approvedAt = schemas.StrSchema
            rejectedAt = schemas.AnyTypeSchema
            paidAt = schemas.StrSchema
            failedAt = schemas.AnyTypeSchema
            pixKey = schemas.AnyTypeSchema
        
            @staticmethod
            def bankAccount() -> typing.Type['RecipientListWithdrawalsResponseDataItemBankAccount']:
                return RecipientListWithdrawalsResponseDataItemBankAccount
        
            @staticmethod
            def recipient() -> typing.Type['RecipientListWithdrawalsResponseDataItemRecipient']:
                return RecipientListWithdrawalsResponseDataItemRecipient
        
            @staticmethod
            def metadata() -> typing.Type['RecipientListWithdrawalsResponseDataItemMetadata']:
                return RecipientListWithdrawalsResponseDataItemMetadata
            __annotations__ = {
                "id": id,
                "code": code,
                "amount": amount,
                "method": method,
                "status": status,
                "createdAt": createdAt,
                "approvedAt": approvedAt,
                "rejectedAt": rejectedAt,
                "paidAt": paidAt,
                "failedAt": failedAt,
                "pixKey": pixKey,
                "bankAccount": bankAccount,
                "recipient": recipient,
                "metadata": metadata,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method"]) -> MetaOapg.properties.method: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["approvedAt"]) -> MetaOapg.properties.approvedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rejectedAt"]) -> MetaOapg.properties.rejectedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paidAt"]) -> MetaOapg.properties.paidAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failedAt"]) -> MetaOapg.properties.failedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pixKey"]) -> MetaOapg.properties.pixKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bankAccount"]) -> 'RecipientListWithdrawalsResponseDataItemBankAccount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recipient"]) -> 'RecipientListWithdrawalsResponseDataItemRecipient': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> 'RecipientListWithdrawalsResponseDataItemMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "code", "amount", "method", "status", "createdAt", "approvedAt", "rejectedAt", "paidAt", "failedAt", "pixKey", "bankAccount", "recipient", "metadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union[MetaOapg.properties.amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method"]) -> typing.Union[MetaOapg.properties.method, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> typing.Union[MetaOapg.properties.createdAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["approvedAt"]) -> typing.Union[MetaOapg.properties.approvedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rejectedAt"]) -> typing.Union[MetaOapg.properties.rejectedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paidAt"]) -> typing.Union[MetaOapg.properties.paidAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failedAt"]) -> typing.Union[MetaOapg.properties.failedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pixKey"]) -> typing.Union[MetaOapg.properties.pixKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bankAccount"]) -> typing.Union['RecipientListWithdrawalsResponseDataItemBankAccount', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recipient"]) -> typing.Union['RecipientListWithdrawalsResponseDataItemRecipient', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union['RecipientListWithdrawalsResponseDataItemMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "code", "amount", "method", "status", "createdAt", "approvedAt", "rejectedAt", "paidAt", "failedAt", "pixKey", "bankAccount", "recipient", "metadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        method: typing.Union[MetaOapg.properties.method, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, schemas.Unset] = schemas.unset,
        approvedAt: typing.Union[MetaOapg.properties.approvedAt, str, schemas.Unset] = schemas.unset,
        rejectedAt: typing.Union[MetaOapg.properties.rejectedAt, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        paidAt: typing.Union[MetaOapg.properties.paidAt, str, schemas.Unset] = schemas.unset,
        failedAt: typing.Union[MetaOapg.properties.failedAt, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        pixKey: typing.Union[MetaOapg.properties.pixKey, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        bankAccount: typing.Union['RecipientListWithdrawalsResponseDataItemBankAccount', schemas.Unset] = schemas.unset,
        recipient: typing.Union['RecipientListWithdrawalsResponseDataItemRecipient', schemas.Unset] = schemas.unset,
        metadata: typing.Union['RecipientListWithdrawalsResponseDataItemMetadata', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RecipientListWithdrawalsResponseDataItem':
        return super().__new__(
            cls,
            *args,
            id=id,
            code=code,
            amount=amount,
            method=method,
            status=status,
            createdAt=createdAt,
            approvedAt=approvedAt,
            rejectedAt=rejectedAt,
            paidAt=paidAt,
            failedAt=failedAt,
            pixKey=pixKey,
            bankAccount=bankAccount,
            recipient=recipient,
            metadata=metadata,
            _configuration=_configuration,
            **kwargs,
        )

from sqala_python_sdk.model.recipient_list_withdrawals_response_data_item_bank_account import RecipientListWithdrawalsResponseDataItemBankAccount
from sqala_python_sdk.model.recipient_list_withdrawals_response_data_item_metadata import RecipientListWithdrawalsResponseDataItemMetadata
from sqala_python_sdk.model.recipient_list_withdrawals_response_data_item_recipient import RecipientListWithdrawalsResponseDataItemRecipient
