# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sqala_python_sdk import schemas  # noqa: F401


class WebhookListAllResponseDataItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def responses() -> typing.Type['WebhookListAllResponseDataItemResponses']:
                return WebhookListAllResponseDataItemResponses
            id = schemas.StrSchema
            event = schemas.StrSchema
        
            @staticmethod
            def object() -> typing.Type['WebhookListAllResponseDataItemObject']:
                return WebhookListAllResponseDataItemObject
            signature = schemas.StrSchema
        
            @staticmethod
            def data() -> typing.Type['WebhookListAllResponseDataItemData']:
                return WebhookListAllResponseDataItemData
            status = schemas.StrSchema
            createdAt = schemas.StrSchema
            queuedAt = schemas.StrSchema
            deliveredAt = schemas.StrSchema
            failedAt = schemas.AnyTypeSchema
            lastAttemptAt = schemas.StrSchema
            nextAttemptAt = schemas.AnyTypeSchema
            endpointId = schemas.StrSchema
            organizationId = schemas.StrSchema
            __annotations__ = {
                "responses": responses,
                "id": id,
                "event": event,
                "object": object,
                "signature": signature,
                "data": data,
                "status": status,
                "createdAt": createdAt,
                "queuedAt": queuedAt,
                "deliveredAt": deliveredAt,
                "failedAt": failedAt,
                "lastAttemptAt": lastAttemptAt,
                "nextAttemptAt": nextAttemptAt,
                "endpointId": endpointId,
                "organizationId": organizationId,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["responses"]) -> 'WebhookListAllResponseDataItemResponses': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["event"]) -> MetaOapg.properties.event: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["object"]) -> 'WebhookListAllResponseDataItemObject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["signature"]) -> MetaOapg.properties.signature: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["data"]) -> 'WebhookListAllResponseDataItemData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["queuedAt"]) -> MetaOapg.properties.queuedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deliveredAt"]) -> MetaOapg.properties.deliveredAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failedAt"]) -> MetaOapg.properties.failedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastAttemptAt"]) -> MetaOapg.properties.lastAttemptAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nextAttemptAt"]) -> MetaOapg.properties.nextAttemptAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["endpointId"]) -> MetaOapg.properties.endpointId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["organizationId"]) -> MetaOapg.properties.organizationId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["responses", "id", "event", "object", "signature", "data", "status", "createdAt", "queuedAt", "deliveredAt", "failedAt", "lastAttemptAt", "nextAttemptAt", "endpointId", "organizationId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["responses"]) -> typing.Union['WebhookListAllResponseDataItemResponses', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["event"]) -> typing.Union[MetaOapg.properties.event, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["object"]) -> typing.Union['WebhookListAllResponseDataItemObject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["signature"]) -> typing.Union[MetaOapg.properties.signature, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["data"]) -> typing.Union['WebhookListAllResponseDataItemData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> typing.Union[MetaOapg.properties.createdAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["queuedAt"]) -> typing.Union[MetaOapg.properties.queuedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deliveredAt"]) -> typing.Union[MetaOapg.properties.deliveredAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failedAt"]) -> typing.Union[MetaOapg.properties.failedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastAttemptAt"]) -> typing.Union[MetaOapg.properties.lastAttemptAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nextAttemptAt"]) -> typing.Union[MetaOapg.properties.nextAttemptAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["endpointId"]) -> typing.Union[MetaOapg.properties.endpointId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["organizationId"]) -> typing.Union[MetaOapg.properties.organizationId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["responses", "id", "event", "object", "signature", "data", "status", "createdAt", "queuedAt", "deliveredAt", "failedAt", "lastAttemptAt", "nextAttemptAt", "endpointId", "organizationId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        responses: typing.Union['WebhookListAllResponseDataItemResponses', schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        event: typing.Union[MetaOapg.properties.event, str, schemas.Unset] = schemas.unset,
        object: typing.Union['WebhookListAllResponseDataItemObject', schemas.Unset] = schemas.unset,
        signature: typing.Union[MetaOapg.properties.signature, str, schemas.Unset] = schemas.unset,
        data: typing.Union['WebhookListAllResponseDataItemData', schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, schemas.Unset] = schemas.unset,
        queuedAt: typing.Union[MetaOapg.properties.queuedAt, str, schemas.Unset] = schemas.unset,
        deliveredAt: typing.Union[MetaOapg.properties.deliveredAt, str, schemas.Unset] = schemas.unset,
        failedAt: typing.Union[MetaOapg.properties.failedAt, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        lastAttemptAt: typing.Union[MetaOapg.properties.lastAttemptAt, str, schemas.Unset] = schemas.unset,
        nextAttemptAt: typing.Union[MetaOapg.properties.nextAttemptAt, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        endpointId: typing.Union[MetaOapg.properties.endpointId, str, schemas.Unset] = schemas.unset,
        organizationId: typing.Union[MetaOapg.properties.organizationId, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WebhookListAllResponseDataItem':
        return super().__new__(
            cls,
            *args,
            responses=responses,
            id=id,
            event=event,
            object=object,
            signature=signature,
            data=data,
            status=status,
            createdAt=createdAt,
            queuedAt=queuedAt,
            deliveredAt=deliveredAt,
            failedAt=failedAt,
            lastAttemptAt=lastAttemptAt,
            nextAttemptAt=nextAttemptAt,
            endpointId=endpointId,
            organizationId=organizationId,
            _configuration=_configuration,
            **kwargs,
        )

from sqala_python_sdk.model.webhook_list_all_response_data_item_data import WebhookListAllResponseDataItemData
from sqala_python_sdk.model.webhook_list_all_response_data_item_object import WebhookListAllResponseDataItemObject
from sqala_python_sdk.model.webhook_list_all_response_data_item_responses import WebhookListAllResponseDataItemResponses
