# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sqala_python_sdk import schemas  # noqa: F401


class WebhookGetResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            id = schemas.StrSchema
            code = schemas.StrSchema
            transactionId = schemas.StrSchema
            amount = schemas.IntSchema
            paidAmount = schemas.IntSchema
            method = schemas.StrSchema
            status = schemas.StrSchema
            createdAt = schemas.StrSchema
            processedAt = schemas.StrSchema
            paidAt = schemas.StrSchema
            failedAt = schemas.AnyTypeSchema
        
            @staticmethod
            def split() -> typing.Type['WebhookGetResponseDataSplit']:
                return WebhookGetResponseDataSplit
        
            @staticmethod
            def payer() -> typing.Type['WebhookGetResponseDataPayer']:
                return WebhookGetResponseDataPayer
        
            @staticmethod
            def source() -> typing.Type['WebhookGetResponseDataSource']:
                return WebhookGetResponseDataSource
        
            @staticmethod
            def destination() -> typing.Type['WebhookGetResponseDataDestination']:
                return WebhookGetResponseDataDestination
            __annotations__ = {
                "id": id,
                "code": code,
                "transactionId": transactionId,
                "amount": amount,
                "paidAmount": paidAmount,
                "method": method,
                "status": status,
                "createdAt": createdAt,
                "processedAt": processedAt,
                "paidAt": paidAt,
                "failedAt": failedAt,
                "split": split,
                "payer": payer,
                "source": source,
                "destination": destination,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactionId"]) -> MetaOapg.properties.transactionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paidAmount"]) -> MetaOapg.properties.paidAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["method"]) -> MetaOapg.properties.method: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["processedAt"]) -> MetaOapg.properties.processedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paidAt"]) -> MetaOapg.properties.paidAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failedAt"]) -> MetaOapg.properties.failedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["split"]) -> 'WebhookGetResponseDataSplit': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payer"]) -> 'WebhookGetResponseDataPayer': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source"]) -> 'WebhookGetResponseDataSource': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["destination"]) -> 'WebhookGetResponseDataDestination': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "code", "transactionId", "amount", "paidAmount", "method", "status", "createdAt", "processedAt", "paidAt", "failedAt", "split", "payer", "source", "destination", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactionId"]) -> typing.Union[MetaOapg.properties.transactionId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union[MetaOapg.properties.amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paidAmount"]) -> typing.Union[MetaOapg.properties.paidAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["method"]) -> typing.Union[MetaOapg.properties.method, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> typing.Union[MetaOapg.properties.createdAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["processedAt"]) -> typing.Union[MetaOapg.properties.processedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paidAt"]) -> typing.Union[MetaOapg.properties.paidAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failedAt"]) -> typing.Union[MetaOapg.properties.failedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["split"]) -> typing.Union['WebhookGetResponseDataSplit', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payer"]) -> typing.Union['WebhookGetResponseDataPayer', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source"]) -> typing.Union['WebhookGetResponseDataSource', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["destination"]) -> typing.Union['WebhookGetResponseDataDestination', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "code", "transactionId", "amount", "paidAmount", "method", "status", "createdAt", "processedAt", "paidAt", "failedAt", "split", "payer", "source", "destination", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        transactionId: typing.Union[MetaOapg.properties.transactionId, str, schemas.Unset] = schemas.unset,
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        paidAmount: typing.Union[MetaOapg.properties.paidAmount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        method: typing.Union[MetaOapg.properties.method, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, schemas.Unset] = schemas.unset,
        processedAt: typing.Union[MetaOapg.properties.processedAt, str, schemas.Unset] = schemas.unset,
        paidAt: typing.Union[MetaOapg.properties.paidAt, str, schemas.Unset] = schemas.unset,
        failedAt: typing.Union[MetaOapg.properties.failedAt, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        split: typing.Union['WebhookGetResponseDataSplit', schemas.Unset] = schemas.unset,
        payer: typing.Union['WebhookGetResponseDataPayer', schemas.Unset] = schemas.unset,
        source: typing.Union['WebhookGetResponseDataSource', schemas.Unset] = schemas.unset,
        destination: typing.Union['WebhookGetResponseDataDestination', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WebhookGetResponseData':
        return super().__new__(
            cls,
            *args,
            id=id,
            code=code,
            transactionId=transactionId,
            amount=amount,
            paidAmount=paidAmount,
            method=method,
            status=status,
            createdAt=createdAt,
            processedAt=processedAt,
            paidAt=paidAt,
            failedAt=failedAt,
            split=split,
            payer=payer,
            source=source,
            destination=destination,
            _configuration=_configuration,
            **kwargs,
        )

from sqala_python_sdk.model.webhook_get_response_data_destination import WebhookGetResponseDataDestination
from sqala_python_sdk.model.webhook_get_response_data_payer import WebhookGetResponseDataPayer
from sqala_python_sdk.model.webhook_get_response_data_source import WebhookGetResponseDataSource
from sqala_python_sdk.model.webhook_get_response_data_split import WebhookGetResponseDataSplit
