# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sqala_python_sdk.paths.itp_payments.post import CreatePaymentInstructionRaw
from sqala_python_sdk.paths.itp_payments_id.get import GetItpRaw
from sqala_python_sdk.paths.itp_payments.get import ListAllRaw


class ITPApiRaw(
    CreatePaymentInstructionRaw,
    GetItpRaw,
    ListAllRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
