# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sqala_python_sdk.paths.pix_qrcode_payments.post import GenerateQrCode
from sqala_python_sdk.paths.pix_qrcode_payments_id.get import GetQrCodeById
from sqala_python_sdk.paths.pix_qrcode_payments.get import ListAll
from sqala_python_sdk.apis.tags.qr_code_api_raw import QRCodeApiRaw


class QRCodeApi(
    GenerateQrCode,
    GetQrCodeById,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: QRCodeApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = QRCodeApiRaw(api_client)
