# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sqala_python_sdk.paths.recipients_recipient_id_bank_accounts.post import CreateBankAccount
from sqala_python_sdk.paths.recipients.post import CreateRecipient
from sqala_python_sdk.paths.recipients_recipient_id_withdrawals.post import CreateWithdrawal
from sqala_python_sdk.paths.recipients_recipient_id_bank_accounts_bank_account_id.delete import DeleteBankAccount
from sqala_python_sdk.paths.recipients_recipient_id_balance.get import GetBalance
from sqala_python_sdk.paths.recipients_recipient_id_bank_accounts_bank_account_id.get import GetBankAccount
from sqala_python_sdk.paths.recipients_id.get import GetById
from sqala_python_sdk.paths.recipients_recipient_id_withdrawals_withdrawal_id.get import GetWithdrawalById
from sqala_python_sdk.paths.recipients.get import ListAll
from sqala_python_sdk.paths.recipients_recipient_id_bank_accounts.get import ListBankAccounts
from sqala_python_sdk.paths.recipients_recipient_id_transactions.get import ListTransactions
from sqala_python_sdk.paths.recipients_recipient_id_withdrawals.get import ListWithdrawals
from sqala_python_sdk.paths.recipients_id.put import UpdateRecipientById
from sqala_python_sdk.apis.tags.recipient_api_raw import RecipientApiRaw


class RecipientApi(
    CreateBankAccount,
    CreateRecipient,
    CreateWithdrawal,
    DeleteBankAccount,
    GetBalance,
    GetBankAccount,
    GetById,
    GetWithdrawalById,
    ListAll,
    ListBankAccounts,
    ListTransactions,
    ListWithdrawals,
    UpdateRecipientById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RecipientApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RecipientApiRaw(api_client)
