# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sqala_python_sdk.paths.recipients_recipient_id_bank_accounts.post import CreateBankAccountRaw
from sqala_python_sdk.paths.recipients.post import CreateRecipientRaw
from sqala_python_sdk.paths.recipients_recipient_id_withdrawals.post import CreateWithdrawalRaw
from sqala_python_sdk.paths.recipients_recipient_id_bank_accounts_bank_account_id.delete import DeleteBankAccountRaw
from sqala_python_sdk.paths.recipients_recipient_id_balance.get import GetBalanceRaw
from sqala_python_sdk.paths.recipients_recipient_id_bank_accounts_bank_account_id.get import GetBankAccountRaw
from sqala_python_sdk.paths.recipients_id.get import GetByIdRaw
from sqala_python_sdk.paths.recipients_recipient_id_withdrawals_withdrawal_id.get import GetWithdrawalByIdRaw
from sqala_python_sdk.paths.recipients.get import ListAllRaw
from sqala_python_sdk.paths.recipients_recipient_id_bank_accounts.get import ListBankAccountsRaw
from sqala_python_sdk.paths.recipients_recipient_id_transactions.get import ListTransactionsRaw
from sqala_python_sdk.paths.recipients_recipient_id_withdrawals.get import ListWithdrawalsRaw
from sqala_python_sdk.paths.recipients_id.put import UpdateRecipientByIdRaw


class RecipientApiRaw(
    CreateBankAccountRaw,
    CreateRecipientRaw,
    CreateWithdrawalRaw,
    DeleteBankAccountRaw,
    GetBalanceRaw,
    GetBankAccountRaw,
    GetByIdRaw,
    GetWithdrawalByIdRaw,
    ListAllRaw,
    ListBankAccountsRaw,
    ListTransactionsRaw,
    ListWithdrawalsRaw,
    UpdateRecipientByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
