# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sqala_python_sdk.paths.webhooks_id.get import Get
from sqala_python_sdk.paths.webhooks.get import ListAll
from sqala_python_sdk.paths.webhooks_id_attempts.post import ResendAttempt
from sqala_python_sdk.apis.tags.webhook_api_raw import WebhookApiRaw


class WebhookApi(
    Get,
    ListAll,
    ResendAttempt,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WebhookApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WebhookApiRaw(api_client)
