# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ItpCreatePaymentInstructionRequestPayer(BaseModel):
    # The customer’s full name or business name.
    name: typing.Optional[str] = Field(None, alias='name')

    # The tax ID of the customer (CPF for individual customers or CNPJ for businesses customers)
    tax_id: typing.Optional[str] = Field(None, alias='taxId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
