# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class RecipientCreateWithdrawalRequestBankAccount(BaseModel):
    # The name of the person or business that owns the bank account.
    holder_name: str = Field(alias='holderName')

    # The tax ID of the account holder (CPF for individual account holders or CNPJ for businesses account holders).
    holder_tax_id: str = Field(alias='holderTaxId')

    # The type of entity that holds the account. Can be INDIVIDUAL or COMPANY.
    holder_type: Literal["INDIVIDUAL", "COMPANY"] = Field(alias='holderType')

    branch_number: str = Field(alias='branchNumber')

    account_number: str = Field(alias='accountNumber')

    # The ID of the bank associated with the account.
    bank_id: str = Field(alias='bankId')

    # The type of bank account. Can be CHEKING or SAVINGS.
    type: typing.Optional[Literal["CHECKING", "SAVINGS"]] = Field(None, alias='type')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
