# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sqala_python_sdk.pydantic.recipient_create_recipient_request_metadata import RecipientCreateRecipientRequestMetadata

class RecipientCreateRecipientRequest(BaseModel):
    # The name of the recipient.
    name: str = Field(alias='name')

    # The tax ID of the recipient (CPF for individual recipients or CNPJ for businesses recipients).
    tax_id: str = Field(alias='taxId')

    # The type of the recipient.
    type: Literal["INDIVIDUAL", "COMPANY"] = Field(alias='type')

    # Unique identifier for the object in your system.
    code: typing.Optional[str] = Field(None, alias='code')

    metadata: typing.Optional[RecipientCreateRecipientRequestMetadata] = Field(None, alias='metadata')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
