# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sqala_python_sdk.pydantic.webhook_list_all_response_data_item_data_destination import WebhookListAllResponseDataItemDataDestination
from sqala_python_sdk.pydantic.webhook_list_all_response_data_item_data_payer import WebhookListAllResponseDataItemDataPayer
from sqala_python_sdk.pydantic.webhook_list_all_response_data_item_data_source import WebhookListAllResponseDataItemDataSource
from sqala_python_sdk.pydantic.webhook_list_all_response_data_item_data_split import WebhookListAllResponseDataItemDataSplit

class WebhookListAllResponseDataItemData(BaseModel):
    id: typing.Optional[str] = Field(None, alias='id')

    code: typing.Optional[str] = Field(None, alias='code')

    transaction_id: typing.Optional[str] = Field(None, alias='transactionId')

    amount: typing.Optional[int] = Field(None, alias='amount')

    paid_amount: typing.Optional[int] = Field(None, alias='paidAmount')

    method: typing.Optional[str] = Field(None, alias='method')

    status: typing.Optional[str] = Field(None, alias='status')

    created_at: typing.Optional[str] = Field(None, alias='createdAt')

    processed_at: typing.Optional[str] = Field(None, alias='processedAt')

    paid_at: typing.Optional[str] = Field(None, alias='paidAt')

    failed_at: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='failedAt')

    split: typing.Optional[WebhookListAllResponseDataItemDataSplit] = Field(None, alias='split')

    payer: typing.Optional[WebhookListAllResponseDataItemDataPayer] = Field(None, alias='payer')

    source: typing.Optional[WebhookListAllResponseDataItemDataSource] = Field(None, alias='source')

    destination: typing.Optional[WebhookListAllResponseDataItemDataDestination] = Field(None, alias='destination')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
