# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sqala_python_sdk.pydantic.webhook_list_all_response_data_item_data import WebhookListAllResponseDataItemData
from sqala_python_sdk.pydantic.webhook_list_all_response_data_item_object import WebhookListAllResponseDataItemObject
from sqala_python_sdk.pydantic.webhook_list_all_response_data_item_responses import WebhookListAllResponseDataItemResponses

class WebhookListAllResponseDataItem(BaseModel):
    responses: typing.Optional[WebhookListAllResponseDataItemResponses] = Field(None, alias='responses')

    id: typing.Optional[str] = Field(None, alias='id')

    event: typing.Optional[str] = Field(None, alias='event')

    object: typing.Optional[WebhookListAllResponseDataItemObject] = Field(None, alias='object')

    signature: typing.Optional[str] = Field(None, alias='signature')

    data: typing.Optional[WebhookListAllResponseDataItemData] = Field(None, alias='data')

    status: typing.Optional[str] = Field(None, alias='status')

    created_at: typing.Optional[str] = Field(None, alias='createdAt')

    queued_at: typing.Optional[str] = Field(None, alias='queuedAt')

    delivered_at: typing.Optional[str] = Field(None, alias='deliveredAt')

    failed_at: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='failedAt')

    last_attempt_at: typing.Optional[str] = Field(None, alias='lastAttemptAt')

    next_attempt_at: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='nextAttemptAt')

    endpoint_id: typing.Optional[str] = Field(None, alias='endpointId')

    organization_id: typing.Optional[str] = Field(None, alias='organizationId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
