# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sqala_python_sdk.type.itp_create_payment_instruction_request_metadata import ItpCreatePaymentInstructionRequestMetadata
from sqala_python_sdk.type.itp_create_payment_instruction_request_payer import ItpCreatePaymentInstructionRequestPayer
from sqala_python_sdk.type.itp_create_payment_instruction_request_split import ItpCreatePaymentInstructionRequestSplit

class RequiredItpCreatePaymentInstructionRequest(TypedDict):
    # Amount in cents to be paid.
    amount: int

    payer: ItpCreatePaymentInstructionRequestPayer

class OptionalItpCreatePaymentInstructionRequest(TypedDict, total=False):
    # Unique identifier for the object in your system.
    code: str

    split: ItpCreatePaymentInstructionRequestSplit

    metadata: ItpCreatePaymentInstructionRequestMetadata

class ItpCreatePaymentInstructionRequest(RequiredItpCreatePaymentInstructionRequest, OptionalItpCreatePaymentInstructionRequest):
    pass
