# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sqala_python_sdk.type.itp_create_payment_instruction400_response_errors import ItpCreatePaymentInstruction400ResponseErrors

class RequiredItpCreatePaymentInstruction400Response(TypedDict):
    pass

class OptionalItpCreatePaymentInstruction400Response(TypedDict, total=False):
    code: str

    message: str

    errors: ItpCreatePaymentInstruction400ResponseErrors

class ItpCreatePaymentInstruction400Response(RequiredItpCreatePaymentInstruction400Response, OptionalItpCreatePaymentInstruction400Response):
    pass
