# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sqala_python_sdk.type.qr_code_generate_qr_code_request_metadata import QrCodeGenerateQrCodeRequestMetadata
from sqala_python_sdk.type.qr_code_generate_qr_code_request_payer import QrCodeGenerateQrCodeRequestPayer
from sqala_python_sdk.type.qr_code_generate_qr_code_request_split import QrCodeGenerateQrCodeRequestSplit

class RequiredQrCodeGenerateQrCodeRequest(TypedDict):
    # Amount in cents to be paid.
    amount: int

class OptionalQrCodeGenerateQrCodeRequest(TypedDict, total=False):
    # Unique identifier for the object in your system.
    code: str

    payer: QrCodeGenerateQrCodeRequestPayer

    split: QrCodeGenerateQrCodeRequestSplit

    metadata: QrCodeGenerateQrCodeRequestMetadata

class QrCodeGenerateQrCodeRequest(RequiredQrCodeGenerateQrCodeRequest, OptionalQrCodeGenerateQrCodeRequest):
    pass
