# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sqala_python_sdk.type.recipient_create_withdrawal_response_bank_account import RecipientCreateWithdrawalResponseBankAccount
from sqala_python_sdk.type.recipient_create_withdrawal_response_metadata import RecipientCreateWithdrawalResponseMetadata
from sqala_python_sdk.type.recipient_create_withdrawal_response_recipient import RecipientCreateWithdrawalResponseRecipient

class RequiredRecipientCreateWithdrawalResponse(TypedDict):
    pass

class OptionalRecipientCreateWithdrawalResponse(TypedDict, total=False):
    id: str

    code: str

    amount: int

    method: str

    status: str

    createdAt: str

    approvedAt: str

    rejectedAt: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    processedAt: str

    paidAt: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    failedAt: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    pixKey: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    bankAccount: RecipientCreateWithdrawalResponseBankAccount

    recipient: RecipientCreateWithdrawalResponseRecipient

    metadata: RecipientCreateWithdrawalResponseMetadata

class RecipientCreateWithdrawalResponse(RequiredRecipientCreateWithdrawalResponse, OptionalRecipientCreateWithdrawalResponse):
    pass
