# coding: utf-8

"""
    Developer API

    At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sqala_python_sdk.type.webhook_get_response_data_destination import WebhookGetResponseDataDestination
from sqala_python_sdk.type.webhook_get_response_data_payer import WebhookGetResponseDataPayer
from sqala_python_sdk.type.webhook_get_response_data_source import WebhookGetResponseDataSource
from sqala_python_sdk.type.webhook_get_response_data_split import WebhookGetResponseDataSplit

class RequiredWebhookGetResponseData(TypedDict):
    pass

class OptionalWebhookGetResponseData(TypedDict, total=False):
    id: str

    code: str

    transactionId: str

    amount: int

    paidAmount: int

    method: str

    status: str

    createdAt: str

    processedAt: str

    paidAt: str

    failedAt: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    split: WebhookGetResponseDataSplit

    payer: WebhookGetResponseDataPayer

    source: WebhookGetResponseDataSource

    destination: WebhookGetResponseDataDestination

class WebhookGetResponseData(RequiredWebhookGetResponseData, OptionalWebhookGetResponseData):
    pass
